// flow-typed signature: 3a668b9d0f146d3e77e8c741ef3be702
// flow-typed version: <<STUB>>/@pumpn/eslint-config_v^0.5.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pumpn/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pumpn/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@pumpn/eslint-config/index' {
  declare module.exports: $Exports<'@pumpn/eslint-config'>;
}
declare module '@pumpn/eslint-config/index.js' {
  declare module.exports: $Exports<'@pumpn/eslint-config'>;
}
